language: python
sudo: required
dist: xenial
python:
- 3.7
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sreyemnayr
  password:
    secure: VGSAK+hccYc1QD2gK9omtyiCQYC/CV5LiqsJApVPTH2Swwq+4237xNOJAF3b2kowPc5ymxJNebpR4uBasKPo7UEL2ts/a8hoh08Ske9MTLH1IEqwKKt/FaUfor8EskOfNrkFx8q+Sz4yHdAdbP/ZVI75xMIDQ8/YNZEgtzmkmA6SN0K5DQrVmPgiYH3QPXOmTzE3QpamlyBET5dPiY0rZ48bgXr6My+l6QBapr4rV0OZVnE4oCUWGbXwNRtQOLdF1UQUdUueQ/EG5feJ3H4NvPm1DNea+NBpf04xaVgyGaqO7OX+L1g8vbpnjqdD0NMBTW9xjytgJVEznqI64xkdu1a2UI+y35LxQ0LR87RZ8zbdf16TGNziK0Lc7dgevVDlAA4ukNiu+TR5kF69yHBrCJqZ+nIkOn7YuIfbt3hYVSRgTqXfBkPAqSttv+r+fX1HR5ltSVFSsDnXwnGPRPYyKDFF/fHYqPC7aXBTMzUZlzL98o+Ia1iFo3XL75bwltIy4lwRbJ9hSq8pIlhO5JtE8PFnR+UjtrY/kPc0wygFUXBxdzRLB1YB1/c0IInLdqBtuecteaaT9fDqnbTWxjUQv6m7tShSC7IS1eC+ey6dO8yC3SyfnqB4ZrtMTEoGrmWOE1h7QzivVdu7RHz0hWPg73TEhP0dU6MtxAVjRALohhk=
  on:
    tags: true
    repo: sreyemnayr/marzano
    python: 3.7
