language: python
sudo: required
dist: xenial
python:
- 3.7
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sreyemnayr
  password:
    secure: YJ/r6WBqgAl2yPMTz1kyKnwNEMzIAZlaom3a7D3hL1tK1T3qqrf2HGPB6s8Ju36tQW5nsypvm6q+7xHr+mpISIMfEWFb/w1d0rERpyleIkZfyrHsiEaAEUh1syCADGh/SYj24UxDPpEmwESYtDyg/Fl7aBUtyvV/86q2vytK5sJOJ61O1i10bfaNczJPsSSVfWUF7U7oHI4F60UoosOU8yAPWvNFm2TlkOxV3hR3bSEX4ZgMan3WMydq63k+7vaCaITRInBGAsfcxS9VK5J9LVnH3p5rWll45AUGjbvVbLGEbI0GX77FLaGR2xPjuma9dEmflCVqXXvfdHnjmDKeTBxZVz+z8/oGrVfwN9xwsRbIe7WNPDEXTopYtgX7alPraL0iEaFRR3sXtO/xWvS2WpMceNpcpK/THf4V3tlzKNIZ5hR1FbKKhsoL5IQd0rj9yaDkFDwLhUjReUBUr4XzEpcLGsbFtAZ4VuSkYfgSojc5BGaC9sFa8V9GUf9fTC1PO1lYAqpReZI2bCEvFa3iui92w3SsI04X8UyGBehsdXwwL7nlu8vmkphLxIj/lyFJRbxr/0DexltNq3cE7aq68x/6yTv1u8q09vbeAYEElvQmvKnQaDwyJUmeGOSe6BzYtrqZalq4FZPucwMt8BUxxqp7mJkwPbn5ZeCVcqSIaG0=
  on:
    tags: true
    repo: sreyemnayr/marzano
    python: 3.7
